name: Build

on: [push, pull_request]

jobs:
  linux_x64:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: '**/requirements.txt'

      - name: Get Version
        run: |
          git fetch --tags --unshallow
          echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build
        run: |
          python setup.py build
          echo "https://github.com/lah7/sims2-ui-inspector" > "dist/View on GitHub.txt"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: "build-linux-x64-${{ env.VERSION }}"
            path: "dist"

  windows_x64:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: '**/requirements.txt'

      - name: Get Version
        run: |
          git fetch --tags --unshallow
          $VERSION = git describe --tags
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build
        run: |
          python setup.py build
          copy .github\github.url "dist\View on GitHub.url"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: "build-windows-x64-${{ env.VERSION }}"
            path: "dist"
